# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actname', models.CharField(max_length=15)),
                ('actdate', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('before', models.BooleanField()),
                ('budget', models.FloatField()),
                ('cost', models.FloatField()),
                ('recive', models.FloatField()),
                ('owner', models.IntegerField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ur', to='step1.User')),
            ],
        ),
    ]
