# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0003_auto_20161115_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='able',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='recive',
            field=models.FloatField(default=True),
        ),
    ]
