# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0004_auto_20161116_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='accept',
            field=models.ManyToManyField(related_name='accept_acts', to='step1.User'),
        ),
        migrations.AlterField(
            model_name='act',
            name='recive',
            field=models.FloatField(default=0.0),
        ),
    ]
