# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0005_auto_20161118_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/huaji2', upload_to='avatars/'),
        ),
    ]
