# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0006_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
