# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0007_act_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='tp',
            field=models.IntegerField(default=0),
        ),
    ]
