# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0008_act_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='twp',
            field=models.ManyToManyField(related_name='twp_acts', to='step1.User'),
        ),
    ]
