# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0009_act_twp'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='p1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='act',
            name='p2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='act',
            name='p3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='act',
            name='p4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='act',
            name='p5',
            field=models.IntegerField(default=0),
        ),
    ]
