# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0011_act_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mnum',
            field=models.IntegerField(default=0),
        ),
    ]
